server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG


example:
  baseUrl: http://localhost:8081

security:
  oauth2:
    client:
      grantType: client_credentials
      clientId: tutorialspoint
      clientSecret: my-secret-key
      accessTokenUri: http://localhost:8081/oauth/token

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration